Add azure arc managed identity
AzureAD/microsoft-authentication-library-for-java pull request #730
Opened 2023-10-17 19:17 UTC by neha-bhargava

2023-10-18 12:35 UTC, bgavrilMS approved these changes

2023-10-18 12:51 UTC, bgavrilMS commented on msal4j-sdk/src/test/java/com/microsoft/aad/msal4j/ManagedIdentityTests.java
> +        lenient().when(httpClientMock.send(any())).thenReturn(response);
Why this lenient mocking? I added the same comment on @Avery-Dunn 's PR about MSI source. Can we get rid of it by resetting the cache?

2023-10-18 12:51 UTC, bgavrilMS requested changes
non-lenient mocking

2023-10-18 19:02 UTC, neha-bhargava commented on msal4j-sdk/src/test/java/com/microsoft/aad/msal4j/ManagedIdentityTests.java
> +        when(httpClientMock.send(eq(expectedRequest(source, resource)))).thenReturn(expectedResponse(200, getSuccessfulResponse(resource)));
@Avery-Dunn with removal of lenient all the tests will fail as the static caching is used. We should have a way to disable static caching for tests. 

Or add cache options like the dotnet have and make it package private for ManagedIdentityApplication

2023-10-22 13:24 UTC, bgavrilMS approved these changes

2023-11-07 15:39 UTC, Avery-Dunn approved these changes

2023-11-09 16:59 UTC, merged